steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/procreators/laravel-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/procreators/laravel-app']
options:
  logging: CLOUD_LOGGING_ONLY
timeout: '1200s'
